//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_Giyim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        public int Email_ID { get; set; }
        public int Kullanici_ID { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
        public string Special1 { get; set; }
        public string Special2 { get; set; }
    }
}
