//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_Giyim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICILAR()
        {
            this.SEPET = new HashSet<SEPET>();
        }
    
        public int Kullanici_ID { get; set; }
        public string Kullanici_Ad { get; set; }
        public string Kullanici_Email { get; set; }
        public string Kullanici_Sifre { get; set; }
        public string Kullanici_Adres { get; set; }
        public Nullable<int> Bakiye { get; set; }
        public int Cinsiyet_ID { get; set; }
        public int Rol_ID { get; set; }
    
        public virtual CINSIYET CINSIYET { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
    }
}
