//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret_Giyim.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.SEPET = new HashSet<SEPET>();
        }
    
        public int Urun_ID { get; set; }
        public string Urun_Ad { get; set; }
        public string Urun_Aciklama { get; set; }
        public int Urun_Fiyat { get; set; }
        public string Urun_Fotograf { get; set; }
        public string Urun_Beden { get; set; }
        public string Urun_Renk { get; set; }
        public string Urun_Marka { get; set; }
        public int Alt_Kategori_ID { get; set; }
        public HttpPostedFileBase File { get; set; }

        public virtual ALT_KATEGORILER ALT_KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
    }
}
